default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USER'] || 'user' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  host: <%= ENV['DATABASE_HOST'] || 'db' %>

development:
  <<: *default
  database: coffee_app_development

production:
  <<: *default
  database: coffee_app_production
  username: <%= ENV['DATABASE_USER'] || 'app_wild_paper_3419' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'late-sun-9601.flycast' %>