default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: user
  password: password

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
